// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtmlcjyvvzqlisyefocj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bWxjanl2dnpxbGlzeWVmb2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNTgzNjgsImV4cCI6MjA4ODczNDM2OH0.eLf7WAUnojsf4EOhz9cHWkW-jyperRJoG1wxGqciumQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});